version: '3.8'

services:
  web:
    build: .
    command: gunicorn rfu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles  # убедитесь, что это соответствует alias в nginx.conf
    depends_on:
      - web

volumes:
  static_volume:
