version: '3'

services:
  web:
    build: .
    command: gunicorn rfu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/bitnami/letsencrypt/certificates:/etc/nginx/certs:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
